_target_: pfp.backbones.pointnet_attention.PointNetAttentionBackbone
embed_dim: ${obs_features_dim}
input_channels: "${eval: '6 if ${dataset.use_pc_color} else 3'}"
input_transform: False
use_group_norm: False
attention_hidden_dim: 256